version: '3'
services:
  serve:
    build: .
    ports:
      - "8000:8000"
    volumes:
     - ./:/docs/:ro
  build:
    build: .
    ports:
      - "8000:8000"
    entrypoint: mkdocs build
    volumes:
     - ./:/docs/:rw
