site_name: Helpbuttons.org
site_description: Description...

repo_url: https://github.com/helpbuttons/hb-docs
edit_uri: https://github.com/helpbuttons/hb-docs


theme:
  name: material
  language: en
  include_search_page: true
  search_index_only: true

plugins:
  - search
  - render_swagger
markdown_extensions:
  - toc:
      permalink: "#"
      toc_depth: 3
  - attr_list
  # - pymdownx.tasklist:
  #     custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/hb-dev/
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/repo
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/hb-dev
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/helpbuttons
