site_name: Helpbuttons Documentation
site_description: Open-source platform for building geo-based collaborative networks
site_url: https://helpbuttons.github.io/hb-docs/

repo_url: https://github.com/helpbuttons/helpbuttons
edit_uri: https://github.com/helpbuttons/hb-docs/edit/main/docs/


theme:
  name: material
  language: en
  include_search_page: true
  search_index_only: true
  logo: images/hb_logo_blue.png
  favicon: images/hb_logo_blue.png

plugins:
  - search
  - render_swagger

markdown_extensions:
  - toc:
      permalink: "#"
      toc_depth: 3
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - English:
    - Overview: English/index.md
    - Philosophy: English/2philosophy.md
    - Features: English/4features.md
    - Core Concepts: English/concepts.md
    - Architecture: English/6architecture.md
    - Pages: English/7pages.md
    - Store: English/9store.md
    - Installation: English/5installation.md
    - Contributing: English/contributing.md
    - Coding Standards: English/coding-standards.md
    - Commit Conventions: English/11commit.md
    - Issues & PRs: English/12issues&PR.md
    - Build Community: English/3buildCommunity.md
    - Contact: English/15contact.md
  - Castellano:
    - Inicio: Castellano/index.md
    - Filosofía: Castellano/filosofia.md
    - Características: Castellano/caracteristicas.md
    - Conceptos: Castellano/conceptos.md
    - Arquitectura: Castellano/arquitectura.md
    - Instalación: Castellano/instalacion.md
    - Páginas: Castellano/paginas.md
    - Normas de código: Castellano/normas-codigo.md
    - Convenciones de commits: Castellano/commits.md
    - Issues y PRs: Castellano/issues-pr.md
    - Construir comunidad: Castellano/construir-comunidad.md
    - Contacto: Castellano/contacto.md
  - API: api.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/helpbuttons
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/helpbuttons
    - icon: fontawesome/brands/mastodon
      link: https://social.coop/@helpbuttons
    - icon: fontawesome/brands/telegram
      link: https://t.me/+-_0KxKJ427VkYjU0
