openapi: 3.0.0
info:
  title: helpbuttons.org
  description: API description
  version: 2.0.0
paths:
  /oauth-clients/local:
    get:
      summary: request a new oauth2 token
      description: You need to retrieve a client id and secret before logging in.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  client_id:
                    type: string
                  client_secret:
                    type: string
                  expires_in:
                    type: integer
                    description: number of seconds to expire the token
              examples:
                token:
                  summary: example token
                  value:
                    client_id: 90286a0bdf0f7315d9d3fe8dabf9e1d2be9c97d0
                    client_secret: 2e0d675df9fc96d2e4ec8a3ebbbf45eca9137bb7
                    expires_in: 14399
  /users/register:
    post:
      summary: register a new account
      tags:
        - users
      description: As a visitor, you can use this API to open an account (if registrations are open on that PeerTube instance). As an admin, you should use the dedicated User creation API instead.
      requestBody:
        content:
          application/json:
            schema:
              title: a new user
              type: object
              properties:
                email:
                  type: string
                  description: email of the user, used for login or service communications
                password:
                  type: string
                  description: password
                username:
                  type: string
                  description: immutable name of the user, used to find or mention its actor
                displayName:
                  type: string
                  description: editable name of the user, displayed in its representations
      responses:
        200:
          description: OK
  /users/{id}/verify-email:
    post:
      summary: verify an email
      tags:
        - users
      description: Following a user registration, the new user will receive an email asking to click a link containing a secret.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: user id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                verificationString:
                  type: string
      responses:
        200:
          description: OK
  /users/{id}/resend-verification-link:
    post:
      summary: resend verification link
      tags:
        - users
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: user id
      responses:
        200:
          description: OK
  /users/{id}/destroy:
    delete:
      summary: delete user account
      tags:
        - users
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: user id
      responses:
        200:
          description: OK
  /users/login:
    post:
      summary: Login to your account
      tags:
        - users
      description: With your client id and secret, you can retrieve an access and refresh tokens.
      requestBody:
        content:
          application/json:
            schema:
              title: login
              type: object
              properties:
                client_id:
                  type: string
                client_secret:
                  type: string
                username:
                  type: string
                  description: immutable name of the user, used to find or mention its actor
                password:
                  type: string
      responses:
        200:
          description: OK
  /users/logout:
    post:
        summary: Logout
        tags:
          - users
        requestBody:
          content:
            application/json:
              schema:
                title: login
                type: object
                properties:
                  access_token:
                    type: string
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: integer
  /users/recover-account:
    post:
        summary: Recover an account
        tags:
          - users
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
        responses:
          200:
            description: OK
  /networks/create:
    post:
        summary: Create a new network
        tags:
          - networks
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  creator_id:
                    type: int
                  net_url:
                    type: string
                  avatar:
                    type: string
                  is_private:
                    type: boolean
                  location_name:
                    type: string
                  location:
                    title: coordinates
                    type: array
                    items:
                      type: integer
                    minItems: 2
                    maxItems: 2
                  created_at:
                    type: datetime
                  updated_at:
                    type: datetime
              examples:
                network:
                  summary: example network
                  value:
                    name: 'Pet Adoption Network'
                    coordinates: [ -9.1790771484375,38.81831117374662]
        responses:
          200:
            description: OK
  /networks/netInfo/create:
    post:
        summary: modify net info
        tags:
          - networks
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  description:
                    type: string
                  button_name:
                    type: string
                  net_modules:
                    type: array
                    items:
                      type: int
                  tags:
                    type: array
                    items:
                      type: tags
        responses:
          200:
            description: OK
          401:
            description: Unauthorized

  /networks/netModerateList/create:
    post:
        summary: create net moderation list
        tags:
          - networks
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  net_id:
                    type: int
                  blocked_users:
                    type: array
                    items:
                      type: int
                  allowed_users:
                    type: array
                    items:
                      types: int
                  roles:
                    type: array
                    items:
                      type: roles
                  friend_nets:
                    type: array
                    items:
                      type: int
        responses:
          200:
            description: OK
          401:
            description: Unauthorized

  /networks/netModerateList/edit:
    put:
        summary: modify net moderation list
        tags:
          - networks
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  net_id:
                    type: int
                  blocked_users:
                    type: array
                    items:
                      type: int
                  allowed_users:
                    type: array
                    items:
                      types: int
                  roles:
                    type: array
                    items:
                      type: roles
                  friend_nets:
                    type: array
                    items:
                      type: int

        responses:
          200:
            description: OK
          401:
            description: Unauthorized

  /networks/destroy:
    delete:
        summary: destruction a network
        tags:
          - networks
        responses:
          200:
            description: OK
          401:
            description: Unauthorized
  /networks/edit:
    put:
        summary: edit a network
        tags:
          - networks
        responses:
          200:
            description: OK
          401:
            description: Unauthorized
  /buttons/create:
    post:
        summary: Create a new button
        tags:
          - buttons
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: int
                  is_active:
                    type: boolean
                  location:
                    title: coordinates
                    type: array
                    items:
                      type: integer
                    minItems: 2
                    maxItems: 2
                  latitude:
                    type: array
                    items:
                      type: float
                  longitude:
                    type: array
                    items:
                      type: float
                  description:
                    type: array
                    items:
                      type: string
                  tags:
                    type: array
                    items:
                      type: tags
                  chats:
                    type: array
                    items:
                      type: integer
                  date:
                    type: array
                    items:
                      type: integer
                  created_at:
                    type: datetime
                  updated_at:
                    type: datetime
              examples:
                button:
                  summary: example button
                  value:
                    type: 1
                    is_active: boolean
                    latitude: [-0.2323]
                    longitude: [9.878788]
                    description: 'NEcesito ayuda para estto y esto'
                    tags: [tag1,tag2,tag3]
                    chats: [1,2,3]
                    date: Lunes, Martes y Miercoles
                    created_at: Nov,10,2020
                    updated_at: Nov,10,2020

                    coordinates: [ -9.1790771484375,38.81831117374662]
        responses:
          200:
            description: OK
  /buttons/destroy:
    delete:
        summary: destroy a button
        tags:
          - buttons
        responses:
          200:
            description: OK
          401:
            description: Unauthorized
  /buttons/edit:
    put:
        summary: edit a button
        tags:
          - buttons
        responses:
          200:
            description: OK
          401:
            description: Unauthorized
  /buttons/buttonTools/create:
    post:
        summary: Create a button extra options
        tags:
          - buttons
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: int
                  is_active:
                    type: boolean
                  created_at:
                    type: datetime
                  updated_at:
                    type: datetime
              examples:
                buttonTools:
                  summary: example buttonTools
                  value:
                    type: 1

                    coordinates: [ -9.1790771484375,38.81831117374662]
        responses:
          200:
            description: OK
  /buttons/buttonTools/destroy:
    delete:
        summary: Clear a button extra options
        tags:
          - buttons
        responses:
          200:
            description: OK
          401:
            description: Unauthorized
  /buttons/buttonTools/edit:
    put:
        summary: Edit button extra options
        tags:
          - buttons
        responses:
          200:
            description: OK
          401:
            description: Unauthorized
  /chats/create:
    post:
        summary: create a chat
        tags:
          - chats
        responses:
          200:
            description: OK
          401:
            description: Unauthorized
  /chats/destroy:
    delete:
        summary: delete a chat
        tags:
          - chats
        responses:
          200:
            description: OK
          401:
            description: Unauthorized
  /chats/edit:
    put:
        summary: Edit a chat
        tags:
          - chats
        responses:
          200:
            description: OK
          401:
            description: Unauthorized
  /messages/create:
    post:
        summary: create a message
        tags:
          - messages
        responses:
          200:
            description: OK
          401:
            description: Unauthorized
  /images/create:
    post:
        summary: create a message
        tags:
          - images
        responses:
          200:
            description: OK
          401:
            description: Unauthorized
  /images/destroy:
    delete:
        summary: delete an image
        tags:
          - images
        responses:
          200:
            description: OK
          401:
            description: Unauthorized
  /languages/create:
    post:
        summary: create a language
        tags:
          - languages
        responses:
          200:
            description: OK
          401:
            description: Unauthorized
  /languages/destroy:
    delete:
        summary: delete a language
        tags:
          - languages
        responses:
          200:
            description: OK
          401:
            description: Unauthorized
  /tags/create:
    post:
        summary: create a tag
        tags:
          - tags
        responses:
          200:
            description: OK
          401:
            description: Unauthorized
  /tags/destroy:
    delete:
        summary: delete a tag
        tags:
          - tags
        responses:
          200:
            description: OK
          401:
            description: Unauthorized
  /interests/create:
    post:
        summary: create an user interest
        tags:
          - interests
        responses:
          200:
            description: OK
          401:
            description: Unauthorized
  /interests/destroy:
    delete:
        summary: delete an user interest
        tags:
          - interests
        responses:
          200:
            description: OK
          401:
            description: Unauthorized
  /interests/edit:
    put:
        summary: Edit an user interest
        tags:
          - interests
        responses:
          200:
            description: OK
          401:
            description: Unauthorized
  /roles/create:
    post:
        summary: create a role
        tags:
          - roles
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  net_id:
                    type: array
                    items:
                      type: int
                  description:
                    type: string
              examples:
                roles:
                  summary: example role
                  value:
                    name: string
                    net_id: int
                    description: string

        responses:
          200:
            description: OK
          401:
            description: Unauthorized
