openapi: 3.0.0
info:
  title: helpbuttons.org
  description: API description
  version: 2.0.0
paths:
  /users/register:
    post:
      summary: register a new user
      description: As a visitor, you can use this API to open an account (if registrations are open on that PeerTube instance). As an admin, you should use the dedicated User creation API instead.
      requestBody:
        content:
          application/json:
            schema:
              title: a new user
              type: object
              properties:
                email:
                  type: string
                  description: email of the user, used for login or service communications
                password:
                  type: string
                  description: password
                username:
                  type: string
                  description: immutable name of the user, used to find or mention its actor
                displayName:
                  type: string
                  description: editable name of the user, displayed in its representations
              required:
                - text
      responses:
        200:
          description: OK
  /users/{id}/verify-email:
    post:
      summary: verify a user
      description: Following a user registration, the new user will receive an email asking to click a link containing a secret.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: user id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                verificationString:
                  type: string
              required:
                - text
      responses:
        200:
          description: OK
  /users/{id}/resend-verification-link:
    post:
      summary: resend verification link to a user
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: user id
      responses:
        200:
          description: OK
  /users/token:
    post:
      summary: You need to retrieve a client id and secret before logging in.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  client_id:
                    type: string
                  client_secret:
                    type: string
  