#!/bin/sh

# Build public content with pandoc-plugin to combine markdown files
## English
docker run --rm -it -v ${PWD}:/docs -e ENABLE_PANDOC_EXPORT=1 robinforgood/mkdocs-material build -f config/en/mkdocs.yml
## Spanish
docker run --rm -it -v ${PWD}:/docs -e ENABLE_PANDOC_EXPORT=1 robinforgood/mkdocs-material build -f config/es/mkdocs.yml

# Generate templates pdfs 
## English
docker run --rm -it -v ${PWD}:/data  robinforgood/latex-pandoc /bin/bash -c 'mkdir -p /assets; cp -r /data/overrides/assets/images /assets/images  ; pandoc -N --template=eisvogel.latex --listings -V lang=en --from markdown --variable mainfont="DejaVuSerif" --variable sansfont="DejaVuSans" --variable monofont="DejaVuSansMono" --variable fontsize=12pt --variable version=2.0 /data/_eng.md /data/public/en/docs.pdf.md  --pdf-engine=xelatex --toc -o /data/pdfs-examples/en/eisvogel_template.pdf; pandoc -N --template=pandoc-scholar.latex --listings -V lang=en --from markdown --variable mainfont="DejaVuSerif" --variable sansfont="DejaVuSans" --variable monofont="DejaVuSansMono" --variable fontsize=12pt --variable version=2.0 /data/pdf_metadata_eng.md /data/public/en/docs.pdf.md  --pdf-engine=xelatex --toc -o /data/pdfs-examples/en/pandoc-scholar_template.pdf;pandoc -N --template=default.latex --listings -V lang=en --from markdown --variable mainfont="DejaVuSerif" --variable sansfont="DejaVuSans" --variable monofont="DejaVuSansMono" --variable fontsize=12pt --variable version=2.0 /data/pdf_metadata_eng.md /data/public/en/docs.pdf.md  --pdf-engine=xelatex --toc -o /data/pdfs-examples/en/default_template.pdf;'
## Spanish
docker run --rm -it -v ${PWD}:/data  robinforgood/latex-pandoc /bin/bash -c 'mkdir -p /assets; cp -r /data/overrides/assets/images /assets/images  ; pandoc -N --template=eisvogel.latex --listings -V lang=es --from markdown --variable mainfont="DejaVuSerif" --variable sansfont="DejaVuSans" --variable monofont="DejaVuSansMono" --variable fontsize=12pt --variable version=2.0 /data/pdf_metadata_esp.md /data/public/es/docs.pdf.md  --pdf-engine=xelatex --toc -o /data/pdfs-examples/es/eisvogel_template.pdf; pandoc -N --template=pandoc-scholar.latex --listings -V lang=es --from markdown --variable mainfont="DejaVuSerif" --variable sansfont="DejaVuSans" --variable monofont="DejaVuSansMono" --variable fontsize=12pt --variable version=2.0 /data/pdf_metadata_esp.md /data/public/es/docs.pdf.md  --pdf-engine=xelatex --toc -o /data/pdfs-examples/es/pandoc-scholar_template.pdf;pandoc -N --template=default.latex --listings -V lang=es --from markdown --variable mainfont="DejaVuSerif" --variable sansfont="DejaVuSans" --variable monofont="DejaVuSansMono" --variable fontsize=12pt --variable version=2.0 /data/pdf_metadata_esp.md /data/public/es/docs.pdf.md  --pdf-engine=xelatex --toc -o /data/pdfs-examples/es/default_template.pdf;'