name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      # - run: git push origin --delete gh-pages
      - run: pip install mkdocs-material mkdocs-pandoc-plugin mkdocs-render-swagger-plugin mkdocs-git-revision-date-localized-plugin
      - run: mkdocs gh-deploy --force
